version: '3.8'

services:
  api:
    build:
      context: ./API/EstoqueAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./FrontEnd/estoque-front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
